### ISSUE TITLE
Unable to execute hook pre_gen.dart fix: 

### ISSUE THREAD

**Issue by wednesdei** [LukeMoody01/mason_bricks#17]
model

- [ x ] model
- 
**Description**
\models> mason make model
? What is the models name? (model) users
? Does this model have a copyWith method? (Y/n) Yes
? Does this model use equatable? (Y/n) Yes
? Does this model use json? (Y/n) Yes
Unable to execute hook: C:/Users/anypo/AppData/Local/Mason/Cache/hosted/registry.brickhub.dev/model_0.3.7\hooks\pre_gen.dart.
Error: Unexpected type 'invalid-type' of a map spread entry.  Expected 'dynamic' or a Map.
    ...context.vars,
               ^

**Steps To Reproduce**

See above

**Expected Behavior**
It creates the model.

**Screenshots**
N/A

**Additional Context**
I'm not sure what I'm doing wrong, but it used to work, any ideas?

**Comment by LukeMoody01** [comment]
Hey @wednesdei 👋

Thanks for opening this issue!

Could you let me know what Mason & Flutter version you are using so I can try to replicate this? Thanks!!

**Comment by maxmblack** [comment]
I am having the same problem with feature_brick (0.5.1)
`
mason make feature_brick --feature_name login --state_management bloc
? Do you want to use equatable with your bloc? (Y/n) (Y/n) No
Could not find lib folder in /Users/max/projects/simplegym/app-v2
Re-run this brick inside your lib folder
An exception occurred while executing hook: /Users/max/.mason-cache/hosted/registry.brickhub.dev/feature_brick_0.5.1/hooks/pre_gen.dart.
Error: Exception
`
Mason: 0.1.0-dev.35
Flutter:  stable, 3.3.2,

**Comment by LukeMoody01** [comment]
Closing this PR as stale. Please feel free to re-open this issue if you have more info!

**Comment by radikris** [comment]
@LukeMoody01 
Same issue here, just with the feature_brick

Mason version
```
(base) admin@Kris---mac features % mason --version
0.1.0-dev.51
```

Flutter version
```
(base) admin@Kris---mac features % flutter --version
Flutter 3.16.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db7ef5bf9f (6 weeks ago) • 2023-11-15 11:25:44 -0800
Engine • revision 74d16627b9
Tools • Dart 3.2.0 • DevTools 2.28.2
```

Dart version
```
(base) admin@Kris---mac features % dart --version
Dart SDK version: 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "macos_arm64"
```

Using the latest feature_brick
bricks:
  hello: 0.1.0+1
  annoying_analysis_options: ^0.0.1
  feature_brick: ^0.6.2
  
`mason make feature_brick --feature_name login --state_management cubit  
`

Error:
```
(base) admin@Kris---mac features % mason make feature_brick --feature_name login --state_management cubit

✓ Compiled pre_gen.dart (2.7s)
An exception occurred while executing hook: /Users/admin/.mason-cache/hosted/registry.brickhub.dev/feature_brick_0.6.2/hooks/pre_gen.dart.
Error: Unable to spawn isolate: Can't load Kernel binary: Invalid kernel binary format version.
```

**Comment by kovilevi98** [comment]
> @LukeMoody01 Same issue here, just with the feature_brick
> 
> Mason version
> 
> ```
> (base) admin@Kris---mac features % mason --version
> 0.1.0-dev.51
> ```
> 
> Flutter version
> 
> ```
> (base) admin@Kris---mac features % flutter --version
> Flutter 3.16.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision db7ef5bf9f (6 weeks ago) • 2023-11-15 11:25:44 -0800
> Engine • revision 74d16627b9
> Tools • Dart 3.2.0 • DevTools 2.28.2
> ```
> 
> Dart version
> 
> ```
> (base) admin@Kris---mac features % dart --version
> Dart SDK version: 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "macos_arm64"
> ```
> 
> Using the latest feature_brick bricks: hello: 0.1.0+1 annoying_analysis_options: ^0.0.1 feature_brick: ^0.6.2
> 
> `mason make feature_brick --feature_name login --state_management cubit `
> 
> Error:
> 
> ```
> (base) admin@Kris---mac features % mason make feature_brick --feature_name login --state_management cubit
> 
> ✓ Compiled pre_gen.dart (2.7s)
> An exception occurred while executing hook: /Users/admin/.mason-cache/hosted/registry.brickhub.dev/feature_brick_0.6.2/hooks/pre_gen.dart.
> Error: Unable to spawn isolate: Can't load Kernel binary: Invalid kernel binary format version.
> ```
> 
> I tried this [workaround](https://rensamatar.medium.com/cant-load-kernel-binary-invalid-kernel-binary-format-version-288d051dde3e):
> 
> ```
> (base) admin@Kris---mac features % which flutter  
> /opt/homebrew/Caskroom/flutter/3.10.5/flutter/bin/flutter
> ```
> 
> and after that `(base) admin@Kris---mac features % rm -rf /opt/homebrew/Caskroom/flutter/3.10.5/flutter/bin/cache/flutter_tools.stamp`
> 
> But issue remains

I have the same issue, is there any solution already?
