### ISSUE TITLE
feat: Add hive as an option to the model brick

### ISSUE THREAD

**Issue by alloza95** [LukeMoody01/mason_bricks#36]
**Brick**

- [x] model
- [ ] feature_brick
- [ ] app_ui
- [ ] service
- [ ] service_package

**Description**

Add the option for a hive model.

**Desired Solution**

Give the user an option to pick a version of the model (freezed, json_serializable, basic, hive).
Uses the enum as a conditional.

**Additional Context**

Hive is used to create models stored in local storage.

**Comment by LukeMoody01** [comment]
This has now been release in the latest version of the model brick! (0.9.0).

Thanks for helping out @alloza95! 👏
