### ISSUE TITLE
feat: cubit option for feature_brick

### ISSUE THREAD

**Issue by yshean** [LukeMoody01/mason_bricks#6]
**Description**

When using BLoC, I always start by using cubits instead of bloc. Is it in the roadmap that you would add one?

**Desired Solution**

Introduce a cubit option when generating a new feature brick

**Additional Context**

I'm still very new to bricks. I might be able to contribute in future when I got to learn more about it.

**Comment by LukeMoody01** [comment]
Hi @yshean 👋
Thanks for opening an issue and good idea!

I’ll make this update later this evening.

**Comment by LukeMoody01** [comment]
This feature has been added in version 3.0 of the brick.

You can find it here: https://brickhub.dev/bricks/feature_brick/0.3.0

Thanks again for opening an issue! 🎉

**Comment by yshean** [comment]
Wow, thanks for the quick update! Keep up the good work 💪
